### ISSUE TITLE
Overriden sensor trigger the alarm

### ISSUE THREAD

**Issue by AGarruchoM** [gazoscalvertos/Hass-Custom-Alarm#15] opened 2018-06-15 17:44 UTC
Dear friend.
When I activate the alarm with an open window, it warns of this one and if you press override it, it is activated with that ignored sensor. After a while the alarm is activated randomly by this sensor.

Thanks!

**Comment by gazoscalvertos** [comment] 2018-06-15 18:41
The intended function of the override is to prevent open sensors from triggering the alarm during the arm phase. Once armed if the sensor then closes it will be included into the monitored sensors so that if it trips it will trigger the alarm. The main use of this is to allow someone to leave one of the doors/motion sensors at the entry point whilst arming the alarm.

Can you tell from you HA logs whether the sensor is closing then reopening?

**Comment by AGarruchoM** [comment] 2018-06-15 18:51
Thank you for your quick response.
The sensor remains open all the time, it does not close again at any time. The sensor history does not show that it changes status at any time.
I think I have the latest version of the alarm but let me make sure.

**Comment by gazoscalvertos** [comment] 2018-06-15 19:05
Hmm, I'll test it on my setup. Typically how long does it take to activate the alarm or is it random?

**Comment by AGarruchoM** [comment] 2018-06-15 19:07
It is random, there are times when it takes hours and hours per second and the alarm is activated.
Tomorrow I'll confirm if I'm using the latest version.

**Comment by gazoscalvertos** [comment] 2018-07-07 00:58
I've tested this on the same settings overnight with a zwave window open before arming the alarm and nothing triggered. 

What kind of sensor is it?

**Comment by AGarruchoM** [comment] 2018-07-07 01:08
All xiaomi windows sensor.
Some times works fine for hours and another times trigger in minuts.

**Comment by gazoscalvertos** [comment] 2019-02-10 21:30
Hi Mate,

Is this still an issue for you? Tested on latest versions with xiaomi aqara devices and can't reproduce the issue. Will close and re-open if its still a problem.

**Closed by gazoscalvertos** 2019-02-10 21:30 UTC
